### ISSUE TITLE
Automatic OWL Generation Memory Error

### ISSUE THREAD

**Issue by mobiusklein** [HUPO-PSI/psi-ms-CV#101]
Since the addition of http://purl.obolibrary.org/obo/stato.owl and http://purl.obolibrary.org/obo/ncit.owl to the CV, `robot` is running out of memory during parsing. Working on diagnosing why.

**Comment by edeutsch** [comment]
I think NCI Thesaurus is enormous..

**Comment by mobiusklein** [comment]
Yes, had to give the JVM 4GB of RAM to work with to get around the issue locally. That should still fly on Github Actions where the limit is 7GB total.
