### ISSUE TITLE
Automatic build failed - Should we remove NCIT?

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/psi-ms-CV#105]
### Describe the question or discussion

It looks like the automatic generation of OWL failed with an out of memory error in the latest build attempt after today's merge.

I wonder if we should remove the import of NCIT. This is such a huge beast and I am doubtful that it is gaining us anything.

**Comment by mobiusklein** [comment]
Will that break mzQC? Is there a restricted subset of NCIT that mzQC depends upon that has its own name?

I can try giving the JVM more memory, but the action worker only has 7 GB of RAM and I was at 4 GB previously.

**Comment by bittremieux** [comment]
We use very few terms from NCIT: currently `Duration` and `Density`, in other mzQC terms that are not merged yet here also `Outlier` and `Cover`(age). These are value concepts that are not super essential, so if it causes issues the NCIT import could relatively safely be avoided I think.

I tried to find alternative terms in other ontologies we import (UO, STATO, PATO):

- [PATO:0001309](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001309): duration
- [STATO:0000333](https://www.ebi.ac.uk/ols/ontologies/stato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSTATO_0000333): density -> kernel mixture distribution. Not ideal.
- [STATO:0000036](https://www.ebi.ac.uk/ols/ontologies/stato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSTATO_0000036): outlier
- No alternative found for "coverage".

**Comment by mwalzer** [comment]
Are there alternative converters that are less memory hungry? 
But yeah, NCIT is a big beast. But as a result of this size, there are a lot of terms for rich semantics in mzQC (don't know about others). 
In the meantime, we could try and get appropriate terms into STATO and PATO. As Wout mentioned, sometimes the definitions are not ideal.

**Comment by mwalzer** [comment]
Pronto can nowadays dump OWL (according to this https://github.com/althonos/pronto/issues/149#issuecomment-1020471399). But I'm having difficulties loading any OBO after I updated...

**Comment by mobiusklein** [comment]
I think we can work around the issue by re-declaring the NCIT terms within our CV unchanged (e.g. using NCIT accessions, but in our file) and that should allow us to use the terms without losing the ability to connect them to other CVs. Right now, the `import` directive is essentially copying _everything_ from NCIT into the MS namespace, so reproducing just the four terms used will suffice.

Source:
https://stackoverflow.com/questions/47695745/referring-to-a-concept-in-a-not-imported-ontology

**Comment by mwalzer** [comment]
Oh wow, didn't know that. Ontologies are a particularly deep well. :hole:

**Comment by edeutsch** [comment]
I vote for removing the NCIT import and explicitly redeclaring at the top of psi-ms.obo the 4 NCIT terms that we want to refer to, and see how it goes.

**Comment by bittremieux** [comment]
Great suggestion @mobiusklein. I've started a PR to do this, but I still have a small question: #109
