### ISSUE TITLE
Instrument term: Xevo G2 XS QTof

### ISSUE THREAD

**Issue by AlanRace** [HUPO-PSI/psi-ms-CV#124]
### Describe the new term or terms you would like to add.

I think the Xevo G2 XS QTof is missing (https://www.waters.com/waters/en_US/Xevo-G2-XS-QTof-Quadrupole-Time-of-Flight-Mass-Spectrometer/nav.htm?cid=134798222&locale=en_US). Term below is modelled on MS:1002729 (Xevo G2 XS Tof).

[Term]
id: MS:XXXXXXX
name: Xevo G2 XS QTof
def: "Waters Corporation Xevo G2 XS QTof orthogonal acceleration time-of-flight mass spectrometer." [PSI:PI]
is_a: MS:1000126 ! Waters instrument model

**Comment by edeutsch** [comment]
Addition merged:
https://github.com/HUPO-PSI/psi-ms-CV/pull/125/files

thanks for the report.
