### ISSUE TITLE
child of MS:1002664 (“interaction score derived from cross-linking”) to record peptide level FDR results

### ISSUE THREAD

**Issue by colin-combe** [HUPO-PSI/psi-ms-CV#153]
### Describe the new term or terms you would like to add.

We think there’s need for a new CV term that is a child of [MS:1002664 (“interaction score derived from cross-linking”)](https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1002664&lang=en&viewMode=All&siblings=false) to record peptide level FDR results. Something like "peptide-pair-level global FDR". There’s a current use case for this with PDBdev.

Is there possibly two different interpretations of "peptide level" depending on whether you do or do not take modifications into consideration when deciding what constitutes a unique peptide?

**Comment by mobiusklein** [comment]
Based upon section 5.2.7 of the mzIdentML 1.2.0 spec, an analysis specifies the peptide grouping rule using one of these terms:
```
[Term]
id: MS:1002496
name: group PSMs by sequence
def: "Group PSMs by distinct peptide sequence ignoring modifications." [PSI:PI]
is_a: MS:1002658 ! identification parameter

[Term]
id: MS:1002497
name: group PSMs by sequence with modifications
def: "Group PSMs by distinct peptide sequence with taking modifications into account." [PSI:PI]
is_a: MS:1002658 ! identification parameter

[Term]
id: MS:1002498
name: group PSMs by sequence with modifications and charge
def: "Group PSMs by distinct peptide sequence with taking modifications and charge into account." [PSI:PI]
is_a: MS:1002658 ! identification parameter
```
and then all subsequent peptide-level statistics related to that analysis use those definitions.

Do you intend to report multiple levels (PSM, single peptidoform, peptidoform pair, combined single peptide, and combined peptide pair) in the same result set? If so, then this grouping mechanism needs to be reworked, and adding additional pair-level group qualifiers. If not, we could add another "level statistic" that hard-codes your semantics, but that might be a quick fix that doesn't generalize well.

**Comment by colin-combe** [comment]
> Do you intend to report multiple levels (PSM, single peptidoform, peptidoform pair, combined single peptide, and combined peptide pair) in the same result set?

I'm not sure, I don't think so. 

My understanding was that we needed terms like the ones you show but as children of MS:1002664 (“interaction score derived from cross-linking”) for recording crosslinking results. @lutzfischer can maybe give a better answer?

**Comment by colin-combe** [comment]
from discussion with @lutzfischer, it seems like its not so clear how to record peptide level FDR results for crosslinking data.

Lutz may put forward a way to do it; otherwise this will remain out of scope for the current round of revisions.

**Comment by colin-combe** [comment]
yeah... basically I think i had the wrong end of the stick when i made this issue. I think @mobiusklein was trying to remind me that a mechanism for all peptide level statistics already exists, separately from the things that were added for residue-residue and protein-protein level FDR for crosslinks.

possibly, the main thing that's missing is a way of stating what the FDR cut off used was? @lutzfischer?

more likely trying to quickly address the FDR questions at this late stage in our revisions is a mistake coz there's gonna be a lot of questions and it'll need discussion with field

**Comment by colin-combe** [comment]
what is needed for FDR is yet to be defined, closing this at moment
