### ISSUE TITLE
Encoding that you searched for all the derivatives of a cleavable crosslinker

### ISSUE THREAD

**Issue by colin-combe** [HUPO-PSI/psi-ms-CV#154]
### Describe the new term or terms you would like to add.

in the context of the new extension document on crosslinking, we think something is needed to encode that you searched for all the derivatives (stubs) of a cleavable crosslinker. 

an example of what was proposed is below, using a new cv term "crosslinker cleavage". 

> Crosslinker cleavage leads to additional stub fragments in the MS2 spectra. To encode that these fragments were searched for the new CV term  “crosslinker cleavage” (MS:XXXXXX) SHOULD be used, one for each stub derivative searched for. The values of  “crosslinker cleavage” (MS:XXXXXX) give the derivative stub mass

it got the following comment:
> "one for each stub derivative searched for" -- This is different from how other CV terms under Peptide/Modification are used. Normally you only print a CV term there for the concrete search result. It can't be the case that the monoisotopic delta 158Da corresponds to three different stubs with different masses.

and in reply:
>This is supposed to signify that the water quenched DSSO monolink is able to be cleaved and throw these 3 stub fragments. All 3 are possible, so they need to be included.
This information is necessary for re-annotation of the spectra.

```
<SequenceCollection>
    	<!-- linear peptides-->
         <Peptide id="p1_linear">
            <PeptideSequence>PEPK</PeptideSequence>
            <Modification location="4" monoisotopicMassDelta="176.01433">
                <cvParam accession="UNIMOD:1842" cvRef="UNIMOD" name="Xlink:DSSO"/>
 		<cvParam accession="MS:XXXXXX" name="UNIMOD derivative code" value="W" cvRef="PSI-MS" />
                
       <cvParam accession="MS:XXXXXX" name="crosslinker cleavage" value="54.0105647" cvRef="PSI-MS"
unitAccession="UO:0000221" unitName="dalton" unitCvRef="UO"/>
       <cvParam accession="MS:XXXXXX" name="crosslinker cleavage" value="103.9932001" cvRef="PSI-MS"
unitAccession="UO:0000221" unitName="dalton" unitCvRef="UO"/>
       <cvParam accession="MS:XXXXXX" name="crosslinker cleavage" value="85.9826354" cvRef="PSI-MS" 
unitAccession="UO:0000221" unitName="dalton" unitCvRef="UO"/>
            </Modification>
        </Peptide>

        <!-- crosslinked peptides -->
<Peptide id="p1">
            <PeptideSequence>PEPK</PeptideSequence>
            <Modification location="4" monoisotopicMassDelta="158.003765">
                <cvParam accession="UNIMOD:1842" cvRef="UNIMOD" name="Xlink:DSSO"/>
                <cvParam cvRef="PSI-MS" accession="MS:1002509" name="cross-link donor" value="1"/>
      <cvParam accession="MS:XXXXXX" name="crosslinker cleavage" value="54.0105647" cvRef="PSI-MS"
unitAccession="UO:0000221" unitName="dalton" unitCvRef="UO"/>
       <cvParam accession="MS:XXXXXX" name="crosslinker cleavage" value="103.9932001" cvRef="PSI-MS"
unitAccession="UO:0000221" unitName="dalton" unitCvRef="UO"/>
       <cvParam accession="MS:XXXXXX" name="crosslinker cleavage" value="85.9826354" cvRef="PSI-MS" 
unitAccession="UO:0000221" unitName="dalton" unitCvRef="UO"/>

            </Modification>
        </Peptide>
        <Peptide id="p2">
            <PeptideSequence>TIDEK</PeptideSequence>
            <Modification location="4" monoisotopicMassDelta="0">
                <cvParam cvRef="PSI-MS" accession="MS:1002510" name="cross-link acceptor" value="1"/>
      <cvParam accession="MS:XXXXXX" name="crosslinker cleavage" value="54.0105647" cvRef="PSI-MS"
unitAccession="UO:0000221" unitName="dalton" unitCvRef="UO"/>
       <cvParam accession="MS:XXXXXX" name="crosslinker cleavage" value="103.9932001" cvRef="PSI-MS"
unitAccession="UO:0000221" unitName="dalton" unitCvRef="UO"/>
       <cvParam accession="MS:XXXXXX" name="crosslinker cleavage" value="85.9826354" cvRef="PSI-MS" 
unitAccession="UO:0000221" unitName="dalton" unitCvRef="UO"/>

            </Modification>
        </Peptide>
```

**Comment by mobiusklein** [comment]
There are a few points that are ambiguous to me:

1. Are the masses in your examples "replacing" the modification mass, or deducting from it?
`<cvParam accession="MS:XXXXXX" name="crosslinker cleavage" value="54.0105647" cvRef="PSI-MS"
unitAccession="UO:0000221" unitName="dalton" unitCvRef="UO"/>`
- I think it's "replacing", but that might differ between acceptor and donor.
- If you could, please show one or two examples where you have a fragment mass with and without the cleaved linker mass to show the semantics. No spectra required, but if that helps make your point, that's fine too.
2. Are these masses linker-specific, peptide-linker-specific, or something the search engine itself decides upon? If they are linker-specific, could these masses go in the CV defining the linker instead of making them a new term? If they go in XLMOD, then we can move the discussion there.
3. Can you define `UNIMOD derivative code` term please? I see it in the mzIdentML extension document, it seems to be referring to a component of the UNIMOD model that is cross-linking specific. I only see it on http://www.unimod.org/modifications_view.php?editid1=1842, but not other DSSO crosslink modifications.

**Comment by vrkosk** [comment]
The Unimod derivative code is described in the help page: http://www.unimod.org/xlink.html

The comment "This is different from how other CV terms ..." was made by me. Behaviour is probably search engine specific, but in Mascot, the linker structure must be defined and known when the search starts. If you do a cleavable crosslink search, the derivative codes are treated as individual variable mods (monolinks). For example, from the Xlink:DSSO entry, the neutral loss with code A (alkene fragment) becomes a variable mod Xlink:DSSO[A] with delta 54Da. The mod and placement that gives the best score is reported as the rank 1 match. If the rank 1 match was made with Xlink:DSSO[A], then the other alternatives were tried but there is never any ambiguity about what was _matched_.

**Comment by colin-combe** [comment]
this has been classed "overreach", won't do this, closing
