### ISSUE TITLE
Do we think releases will work now?

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/psi-ms-CV#161]
### Describe the question or discussion

I notice that master is currently on version 103:
https://github.com/HUPO-PSI/psi-ms-CV/commit/97f77de2ce2a2c0edb4123d3796e4a0c0ac44441

but the most recent release is 100:
https://github.com/HUPO-PSI/psi-ms-CV/releases

Do we think that our release problems have been fixed? And with the next push, the release should work?

Or is there more troubleshooting to be done?

**Comment by mobiusklein** [comment]
It seems my fix for circumventing branch protection didn't work. I'll try something else later today.

**Comment by edeutsch** [comment]
I see that 103 is now released, thank you!!
