### ISSUE TITLE
Add terms for lipid shorthand identification confidence level and lipid empirical score

### ISSUE THREAD

**Issue by nilshoffmann** [HUPO-PSI/psi-ms-CV#164]
### Describe the new term or terms you would like to add.

I would like to request two new terms related to lipid identification with mass spectrometry.
The first one extends the existing concept of small molecule identification attribute and confidence levels that were introduced for mzTab-M by one that specifically reflects the level of structural knowledge about a lipid identified with MS. This level immediately translates to a shorthand name that encodes the lipid class and additional, level-specific structural details. The levels of the lipid shorthand identification confidence level correspond to the levels defined within the lipid shorthand nomenclature as recently updated in PMID:33037133. These names are used by LIPID MAPS, SwissLipids, RefMet and other resources.
```
[Term]
id: MS:100XXXX
name: Lipid shorthand identification confidence level
def: "Identification confidence levels based on the updated lipid shorthand nomenclature. The value slot can have the values 'Category', 'Class', 'Species', 'Phosphate-position', 'Molecular species', 'sn-position', 'DBE position', 'Structure defined', 'Full structure', 'Complete structure'." [PMID:33037133]
is_a: MS:1002895 ! small molecule identification attribute
relationship: has_value_type xsd:string ! The allowed value-type for this CV term
```
The second term introduces the concept of an empirical score for lipids identified with MS, based on lipid class- and method-specific theoretically possible point contributions. The score is normalized between 0-100, where 100 would be the maximally attainable score for a specific lipid where all possible sources of evidence have been used for identification. Scores between lipid classes are generally not comparable, since their analytics may differ substantially. A manuscript introducing this score is currently being prepared.
```
[Term]
id: MS:100XXXX
name: Lipid empirical score
def: "The lipid empirical score is a point-based lipid class-specific scoring system based on MS and other evidence sources as defined by the Lipidomics Standards Initiative (LSI). The score has a numeric value between 0 and 100. Score values are lipid class-specific and are therefore not immediately comparable between lipid classes." [PMID:NA]
is_a: MS:1002888 ! small molecule confidence measure
relationship: has_value_type xsd:float ! The allowed value-type for this CV term
```

**Comment by nilshoffmann** [comment]
Please note that we debated, whether the terms should receive a sort of version indicator, but since I have not seen anything like that in PSI-MS before, I have opted to request plain terms. Would the referenced publication usually be sufficient to serve as a version indicator?

**Comment by mobiusklein** [comment]
If you would like the `Lipid shorthand identification confidence level` term to enforce its values only matching that list, and if you expect it to change in a backwards incompatible way, you'll likely want a new term in the future, but we can't know which publication is cited directly from a document unless its encoded somehow. 

In order of least to most work:
1. Request a new term if/when a new term is needed, and then new software can use the new term without needing to tack on a "v1" now.
2. Add a version signifier now. 
3. Labor heroically to never be backwards incompatible.
4. Create a new CV term for each "level" that is in `Lipid shorthand identification confidence level` that inherits from it via an `is_a` and create new terms when a new meaning is needed.
5. Create a new vocabulary which governs these values and their meaning and version it, referencing the appropriate version in documents which use a newer version of these levels

I think option 1 is the most parsimonious, but then I don't know the domain and how likely it is to change. I think option 4 is the best compromise.

If you expect `Lipid empirical score` to change, I think you should just request another term when that happens for backwards compatibility. 

Is `Lipid empirical score` a "higher-is-better" quantity?

**Comment by nilshoffmann** [comment]
My gut feeling would say that option 4 makes sense, since there may be some intermediate levels that will be added in the future, as analytical technology improves, but it is unlikely, that the concept as such will be changed dramatically. And if so, a new term would help us out.

`Lipid empirical score` is  a "higher-is-better" quantity in the sense of a capped / normalized score. However, it is tied to structural / analytical properties of each lipid class and therefor specific and not comparable between lipid classes.

**Comment by nilshoffmann** [comment]
Option 4 could be encoded as follows in mzTab-M (in principle): [MS, MS:100XXXX, Lipid shorthand identification confidence level, MS:100XXXY] This should have the least impact on existing implementations and would only require changes in semantic validation.

**Comment by edeutsch** [comment]
Resolved with PR https://github.com/HUPO-PSI/psi-ms-CV/pull/169
