### ISSUE TITLE
regex syntax for MS:1002505 (regular expression for modification localization scoring)

### ISSUE THREAD

**Issue by colin-combe** [HUPO-PSI/psi-ms-CV#171]
### Describe the question or discussion

Hi,
@lutzfischer and I had a go at updating/fixing the regex syntax for MS:1002505 (regular expression for modification localization scoring).

We propose:
`([0-9]+):([01][.][0-9]+(?:[Ee][+\-]?[0-9]+)?):([0-9]+(?:[|][0-9]+)*):(true|false)`

we think this follows the syntax and use of capturing groups used by @mobiusklein in issue #142

The purpose of the regex is given in Section 5.2.8 of the mzIdentML 1.2.0 spec (pg. 17)
see also https://regex101.com/r/ZM1jTJ/1

**Comment by colin-combe** [comment]
related #64

**Comment by mobiusklein** [comment]
Mapping the slot labels from the spec onto the Regex using ECMA's syntax:
`(?<MOD_INDEX>[0-9]+):(?<SCORE>[01][.][0-9]+(?:[Ee][+\-]?[0-9]+)?):(?<POSITION>[0-9]+(?:[|][0-9]+)*):(?<PASS_THRESHOLD>true|false)`

This looks good to me.

I can update the CV and submit a PR for this, pending any other comments.

**Comment by colin-combe** [comment]
should we ignore the case of 'true' and 'false'?

if so, i'm not sure of the best way to do it because the "/i" flag at the end would be outside the bit of the regex we show, if you know what I mean. Other ways of doing it don't seem to work in all regex flavours. (@lutz)

we could just write `true|TRUE|false|FALSE`, though that's not exactly the same as being case insensitive
