### ISSUE TITLE
CV tag for Top-Down Proteomics software

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/psi-ms-CV#176]
### What is the new software's name?

FLASHDeconv

### Describe the software briefly.

I imagine it would look like this:
```
[Term]
id MS:1000xxx
name: FLASHDeconv
def: Ultrafast, High-Quality Feature Deconvolution for Top-Down Proteomics  [DOI: 10.1016/j.cels.2020.01.003]
is_a: MS:1001456 ! analysis software
is_a: MS:1001457 ! data processing software
```

### Describe any additional information.

do we need a separate category? (#144 might be useful...)

**Comment by mwalzer** [comment]
@KyowonJeong

**Comment by KyowonJeong** [comment]
Looks great!
