### ISSUE TITLE
Add "SelexION differential mobility separation device"

### ISSUE THREAD

**Issue by sneumann** [HUPO-PSI/psi-ms-CV#178]
### Describe the new term or terms you would like to add.

Hi, we need a term `SelexION differential mobility separation device` .

**Comment by mobiusklein** [comment]
This is to be used as a component in instrument configuration in mzML, correct? Would it be in the `source`, `analyzer`, or `detector`? I would suspect `analyzer`.

We don't have an equivalent term for another frontend ion mobility separation addon, so this may set the standard for FAIMS as well.

**Comment by sneumann** [comment]
Hi, sorry if the initial issue description was a bit terse, it came out of "Proposed [IM-MS and DIA best practiced document](https://github.com/HUPO-PSI/mzML/blob/master/specification_document/mzML_1.1.0_UseCaseRecommendationForDIAandIMSdata_v0.9.5.docx?raw=true) version 0.9.5" on https://psidev.info/mzML and I extracted a comment and upgraded it to an issue here. 
I myself would not have a definite answer at the moment.  Yours, Steffen

**Comment by edeutsch** [comment]
addressed in #191
