### ISSUE TITLE
minor correction to MS:1003333 in update for mzIdentML 1.2.1

### ISSUE THREAD

**Issue by colin-combe** [HUPO-PSI/psi-ms-CV#181]
### Describe the question or discussion

minor mistake made by me for term MS:1003333
```
[Term]
id: MS:1003333
name: regular expression for encoding identifications based on multiple spectra.
def:  "^(?<MULTIPLE_SPECTRA_IDENTIFIER>[0-9]+):(?<PARENT_OR_CHILD>P|C)$" [PSI:MS]
is_a: MS:1002479 ! regular expression
```
we said the P or C should be optional:
```
[Term]
id: MS:1003333
name: regular expression for encoding identifications based on multiple spectra.
def:  "^(?<MULTIPLE_SPECTRA_IDENTIFIER>[0-9]+):(?<PARENT_OR_CHILD>P|C)?$" [PSI:MS]
is_a: MS:1002479 ! regular expression
```
(addition of question mark after PARENT_OR_CHILD capturing group, @lutzfischer )
https://regex101.com/r/zzxSeT/1
thanks,
Colin

**Comment by mobiusklein** [comment]
If the `P|C` group is absent, should there still be a trailing `:`? I would say "no"?

That's make the regex `^(?<MULTIPLE_SPECTRA_IDENTIFIER>[0-9]+)(?::(?<PARENT_OR_CHILD>P|C))?$`

**Comment by colin-combe** [comment]
ok, i did wonder about this...
i left the colon in thinking, in a way, it signified the absence of P or C
but you're probably right - its a bit weird and i think your way is better
(what we've written in docs is unclear about whether the colon stays or goes, i'll clarify that too)
