### ISSUE TITLE
ANN-SoLo 

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/psi-ms-CV#184]
### What is the new software's name?

ANN-SoLo

### Describe the software briefly.

From the [GitHub repo](https://github.com/bittremieux/ANN-SoLo):
ANN-SoLo (Approximate Nearest Neighbor Spectral Library) is a spectral library search engine for fast and accurate open modification searching. ANN-SoLo uses approximate nearest neighbor indexing to speed up open modification searching by selecting only a limited number of the most relevant library spectra to compare to an unknown query spectrum. This is combined with a cascade search strategy to maximize the number of identified unmodified and modified spectra while strictly controlling the false discovery rate and the shifted dot product score to sensitively match modified spectra to their unmodified counterpart.

### Software type

MS:1001456 ! analysis software

### Describe any additional information.

[doi:10.1021/acs.jproteome.8b00359]
[doi:10.1021/acs.jproteome.9b00291]

**Comment by mwalzer** [comment]
@bittremieux any more software types?

**Comment by bittremieux** [comment]
No, I think this is fine.

**Comment by edeutsch** [comment]
Addressed in #189
