### ISSUE TITLE
iRT calibration formula

### ISSUE THREAD

**Issue by bittremieux** [HUPO-PSI/psi-ms-CV#187]
### What is the QC term's name?

iRT calibration formula

### Briefly describe the QC term.

A polynomial formula to calibrate retention time based on iRT reference peptides. The order of the values corresponds to polynomial terms. I.e. a linear equation is represented by a two-tuple consisting of (slope, intercept). More general, the position in the n_tuple indicates the power of `x`: position `n` → `x^0`, position `n - 1` → `x^1`, position `n - 2` → `x^2`, etc.

### Value type

MS:4000004 ! n-tuple

**Comment by edeutsch** [comment]
Addressed in #189
