### ISSUE TITLE
New class suggestions for PSI-MS

### ISSUE THREAD

**Issue by janelomax** [HUPO-PSI/psi-ms-CV#19]
1. term: Tandem Mass Spectrometry
synonyms: MS/MS, MS2
definition:  Technique to isolate ions (peptides) and subject ions to fragmentation.
xref: http://purl.obolibrary.org/obo/NCIT_C18142

2. term: in-gel digestion
synonyms: in-gel digest, In-Gel Tryptic Digestion
definition: Digestion of proteins separated by gel electrophoresis for mass spectrometric characterization of proteins and proteomes.
(perhaps a subclass of http://purl.obolibrary.org/obo/MS_1000831?)

3. term: in-solution digestion
synonyms: in-solution digest
definition: Digestion of proteins in solution for mass spectrometric characterization of proteins and proteomes.
(perhaps a subclass of http://purl.obolibrary.org/obo/MS_1000831?)

**Comment by germa** [comment]
1. We have already in psi-ms.obo a term for MS2 search:
[Term]
id: MS:1001083
name: ms-ms search
def: "An MS2 search (with fragment ions)." [PSI:PI]
is_a: MS:1001080 ! search type

2. + 3. added in version 4.1.16
