### ISSUE TITLE
new term for version of crosslinking extension document 

### ISSUE THREAD

**Issue by colin-combe** [HUPO-PSI/psi-ms-CV#196]
### Describe the new term or terms you would like to add.

Hi Joshua (@mobiusklein),
assuming I've correctly understood how the new MS:1003372 and MS:1003373 terms are meant to work, 
and bearing in mind the text you wrote in the draft 1.3.0 spec: "A document signals which extensions it requires by including a cvParam that is a child of MS:1003373",
then I think the new CV term for the version of the crosslinking extension document is yet to be created?

I think we need a new CV term, child of MS:1003373, with name "mzIdentML crosslinking extension document version", or similar?

We could consider making the value of MS:1003373 a regex that describes semantic versioning rather than a string. Or do you think that's overkill?

Thanks for your help,
Colin

**Comment by mobiusklein** [comment]
Apologies for the delay in response. My supposition when I wrote that term tree a few weeks ago was to not enforce semantic versioning and to allow extensions to govern their own versioning and how they should be signaled. Part of this is because we cannot test the extension names ahead of time, but I suppose we could just use a regex that forces the semver to be at the end:
```js
/(.+)\sv?(\d+)\.(\d+)\.(\d+)$/
```
I'll try testing that and update the term accordingly.

**Comment by colin-combe** [comment]
> Apologies for the delay in response.

no problem

>Part of this is because we cannot test the extension names ahead of time, but I suppose we could just use a regex that forces the semver to be at the end

Yes, this is the point i was trying to get to - if "a document signals which extensions it requires by including a cvParam that is a _child of MS:1003373 (mzIdentML extension version)_", then, potentially, the extension name will not be in the value of the cv term but in its name? 

E.g. if the version of the crosslinking extension doc is signalled with a child of MS:1003373, then we need a new cv term (child of "mzIdentML extension version") for "mzIdentML crosslinking extension document version", and then the name of the extension is in the name of the cv term and the value can be only the version?

I wasn't sure if this was what you intended, but it's sort of implied by what you wrote in the spec doc. Sorry for labouring the point. When @lutzfischer and I looked at this, we thought this way of doing it might be better, even if it wasn't the initial intention.
 
Also, i think semver is the only sensible versioning system.

Can discuss... Juan asked for a mzIdentML meeting next Tues (see email) but the time was set without actually checking whether people are free to attend.
