### ISSUE TITLE
Term obsolete

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/psi-ms-CV#20]
This term is obsolete https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1001016 but no option is provided. The current mzIdnetML and mztab hardcode this information directly into a prop[erty database version. But the term can exist also in case someone want to translate this.

**Comment by germa** [comment]
Reactivated the term in version 4.1.23
