### ISSUE TITLE
New term for Instrument Model Systems

### ISSUE THREAD

**Issue by lnanderson** [HUPO-PSI/psi-ms-CV#219]
### Describe the new term or terms you would like to add.

I would like to suggest the following new term additions for the [Thermo Fisher Q Exactive GC Orbitrap GC-MS/MS system](https://www.thermofisher.com/order/catalog/product/0725500#/0725500), [Agilent 8890 GC/MS system](https://www.agilent.com/en/product/gas-chromatography/gc-systems/8890-gc-system), and [Bruker timsTOF flex 2](https://www.bruker.com/en/products-and-solutions/mass-spectrometry/timstof/timstof-flex-maldi-2.html).

[Term]
id: MS:100xxxx
name: Q Exactive GC
def: Q Exactive GC Orbitrap GC-MS/MS hybrid quadrupole Orbitrap mass spectrometer.
is_a: MS:1000483 ! Thermo Fisher Scientific instrument model

[Term]
id: MS:100xxxx
name: 8890 GC/MS
def: Agilent 8890 Gas Chromatography system.
is_a: MS:1000490 ! Agilent instrument model

[Term]
id: MS:100xxxx
name: timsTOF flex 2
def: Bruker Daltonics' timsTOF fleX MALDI-2.
is_a: MS:1003123 ! Bruker Daltonics timsTOF series

**Comment by edeutsch** [comment]
Addressed in #220

**Comment by lnanderson** [comment]
@edeutsch thank you!
