### ISSUE TITLE
New Term

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/psi-ms-CV#23]
@germa we need to add the following CVTerm: 

`CPTAC accession number`

Similar to the term for proteomeXchange: 

https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1001919

**Comment by edeutsch** [comment]
Do they even have accession numbers?
The hope is that Nuno and MassIVE are going to assign PXD accession numbers for all CPTAC datasets any day now. Maybe tomorrow? Do we really need this? Okay if we do..

**Comment by germa** [comment]
added to version 4.1.31
