### ISSUE TITLE
New Term for MS-DIAL software

### ISSUE THREAD

**Issue by nilshoffmann** [HUPO-PSI/psi-ms-CV#24]
I would like to request a new software term added for MS-DIAL

http://prime.psc.riken.jp/Metabolomics_Software/MS-DIAL/

I think it belongs below MS:1002878 (small molecule software) since it is described to apply to both metabolomics and lipidomics.

id	MS:XXXXXXX
name	MS-DIAL
def	"MS-DIAL is a universal program for untargeted metabolomics and lipidomics that supports multiple instruments and MS vendors." [PMID:25938372]
is_a	MS:1002878 small molecule software ! small molecule software
is_a	MS:1001457 data processing software ! data processing software

**Comment by mobiusklein** [comment]
Noticed that when traversing by comment, "small molecule software" fails to resolve. The accession listed is named "small molecule analysis software"

**Comment by edeutsch** [comment]
Ah, you are correct that under term MS:1003082, it should be:
is_a: MS:1002878 ! small molecule analysis software
instead of:
is_a: MS:1002878 ! small molecule software

@germa would you make that change?

**Comment by nilshoffmann** [comment]
Correct, I must have lost the "analysis" part somewhere. Sorry!

**Comment by sneumann** [comment]
Has been added as `id: MS:1003082` in https://github.com/HUPO-PSI/psi-ms-CV/blob/e952123028b798e1dbb1abaef1ba8a0366836598/psi-ms.obo#L19683. 
Can be closed now. Yours, Steffen

**Comment by nilshoffmann** [comment]
Thanks!
