### ISSUE TITLE
A QC metric to track the duration it takes to 'accumulate' each subsequent quarter of identified spectra

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/psi-ms-CV#243]
### What is the QC term's name?

identified MS2 quarter RT fraction

### Briefly describe the QC term.

The interval in which the first, second, third, and fourth quarter of all identified MS2 events are, divided by retention time duration. The metric informs about the dynamic range of the MS2 identification process along the chromatographic separation. For MS2 scans, the comparability of the values depends on the acquisition mode and settings to select ions for fragmentation.

### What is the QC term's unit?

It's a fraction (s/s)

### Value type

MS:4000004 ! n-tuple

### Describe any additional information.

Term entry proposition:
```
[Term]
id: MS:4000xxx
name: identified MS2 quarter RT fraction
def: "The interval in which the first, second, third, and fourth quarter of all identified MS2 events are, divided by retention time duration." [PSI:MS]
comment: The metric informs about the dynamic range of the MS2 identification process along the chromatographic separation. For MS2 scans, the comparability of the values depends on the acquisition mode and settings to select ions for fragmentation.
is_a: MS:4000004 ! n-tuple
relationship: has_metric_category MS:4000008 ! ID based metric
relationship: has_metric_category MS:4000012 ! single run based metric
relationship: has_metric_category MS:4000016 ! retention time metric
relationship: has_value_type xsd:float ! The allowed value-type for this CV term
relationship: has_units UO:0000191 ! fraction
```

**Comment by cbielow** [comment]
maybe add 
```
synonym: "RT-MS-Q1" RELATED [PMID:24494671]
synonym: "RT-MS-Q2" RELATED [PMID:24494671]
synonym: "RT-MS-Q3" RELATED [PMID:24494671]
synonym: "RT-MS-Q4" RELATED [PMID:24494671]
```
to give some hint on what exactly these 4 quarters are? But maybe even better, we should be more concise in the definition, so people to not need to read a paper to understand what is meant here?

**Comment by cbielow** [comment]
as discussed, this wording may need a little tinkering, i.e.
given [p0, p25, p50,p75,p100] as percentiles of the above MS2 event distributions in unit of seconds, what this actually computes is
{ (p25 - p0) / (p100 - p0),
  (p50 - p25) / (p100 - p0),
 ....}

even though I'm not sure if 'RT duration' is its total duration or just the span in which IDs are observed. The implications are quite different.

**Comment by mwalzer** [comment]
I would not bring in quantiles or percentiles into the explanation. The fewer concepts the more accessible, imo. 
Dividing by 'id-span' sounds interesting, but what would that tell you? How evenly the gradient separates the sample? But it would exclude start/end phases where identification might be hindered by other factors. I'd go for total now.
```
def: "The retention time interval in which the first, second, third, and fourth quarter of all identified MS2 events, ordered by retention time, are recorded, each divided by total retention time duration." [PSI:MS]
comment: The metric informs about the dynamic range of the MS2 identification process along the chromatographic separation. For MS2 scans, the comparability of the values depends on the acquisition mode and settings to select ions for fragmentation.

```

**Comment by tnaake** [comment]
Just as a side note, there is already one term that is similar to this one, [MS:4000056](https://github.com/HUPO-PSI/psi-ms-CV/blob/master/psi-ms.obo#L22699), which misses the "identified" part.

**Comment by bittremieux** [comment]
Completed in #255.
