### ISSUE TITLE
New terms for mzMLb compression

### ISSUE THREAD

**Issue by awd97** [HUPO-PSI/psi-ms-CV#25]
A while back some terms for our new mzMLb hybrid HDF5/XML file format were incorporated into the obo. Now that the manuscript is uploaded to bioRxiv (https://www.biorxiv.org/content/10.1101/2020.02.13.947218v1), we would like to add three further terms. These were specifically designed for mzMLb but also work fine with mzML etc. They require one integer parameter that specifies the level of truncation. They do not help if no compression is used, so I think it would be best to incorporate them into the obo in the same form as the MS-Numpress ones. i.e.:

[Term]
name: truncation and zlib compression
def: "Compression using truncation and zlib." [https://github.com/biospi/pwiz]
xref: value-type:xsd\:int "The number of mantissa bits truncated."
is_a: MS:1000572 ! binary data compression type

[Term]
name: truncation, delta prediction and zlib compression
def: "Compression using truncation, delta prediction and zlib." [https://github.com/biospi/pwiz]
xref: value-type:xsd\:int "The number of mantissa bits truncated."
is_a: MS:1000572 ! binary data compression type

[Term]
name: truncation, linear prediction and zlib compression
def: "Compression using truncation, linear prediction and zlib." [https://github.com/biospi/pwiz]
xref: value-type:xsd\:int "The number of mantissa bits truncated."
is_a: MS:1000572 ! binary data compression type 

Best wishes,
Andy

**Comment by edeutsch** [comment]
Two comments:

1) I do not think it such a good idea to have a single concept for a chain of concepts (and then multiple terms/concepts for different combinations individual concepts). I think it would be better to separate them, one term of zlib compression (which I think already exists?), one term for mantissa truncation, one term for delta prediction and one for linear prediction. They can be used in whatever combination appropriate.

2) I think we should avoid having a concept that an algorithm was applied (where a value is not appropriate) and then tacking on a value that is really a different concept. I think the concept of mantissa truncation is a separate thing than the concept of the number of mantissa bits that are truncated. it's tempting to combine them, but I would suggest against it. If we don't want to report two terms all the time, then using the term "number of mantissa bits truncated" could serve as a flag that mantissa truncation was performed. i.e. if a term takes a value, the term really should be describing the concept of what the value is.

Comments?

**Comment by awd97** [comment]
I suggested it this way first because it appeared concepts were already chained with the numpress CVs (e.g. 'MS-Numpress linear prediction compression followed by zlib compression'). Note that the order of these concepts is fairly important, for writing truncation is performed first, then delta or linear prediction, and then finally zlib compression.

We could split these concepts into three separate things, or perhaps into two things which would keep things consistent with NumPress?: (1) number of mantissa bits truncated, and (2) delta/linear compression followed by zlib compression (same as numPress CVs, although note since our delta/linear prediction doesn't do any compression by itself, I only include CVs that include subsequent zlib compression).

[Term]
name: number of mantissa bits truncated
def: "Number of mantissa bits truncated to improve subsequent compression." 
xref: value-type:xsd:int "The number of mantissa bits truncated."

[Term]
name: mzMLb delta prediction followed by zlib compression
def: "Compression using mzMLb delta prediction and zlib." [https://github.com/biospi/pwiz]
is_a: MS:1000572 ! binary data compression type

[Term]
name: mzMLb linear prediction followed by zlib compression
def: "Compression using MS-Numpress linear prediction and zlib." [https://github.com/biospi/pwiz]
is_a: MS:1000572 ! binary data compression type

**Comment by awd97** [comment]
bump :-)

**Comment by edeutsch** [comment]
@awd97 please review pull request https://github.com/HUPO-PSI/psi-ms-CV/pull/28

**Comment by awd97** [comment]
As I understand it, the proposal is to have one of the three terms proposed in my first post + the number of mantissa bits truncated as a separate term as proposed in my second post. If so, that is fine!

**Comment by edeutsch** [comment]
The proposal is to have all 3 of the terms from your first post (except slightly modified to NOT have a value) plus the number of mantissa bits truncated as a separate term as proposed in your second post. Delta is here:
https://github.com/HUPO-PSI/psi-ms-CV/pull/28/files

Note that @ypriverol has already merged the pull request. But if you have concerns, changes can still be made.

**Comment by awd97** [comment]
looks fine, cheers
________________________________

**Comment by sneumann** [comment]
I guess this could be closed now ? Yours, Steffen
