### ISSUE TITLE
URGENT Revert to previous owl generation

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/psi-ms-CV#268]
### Describe the question or discussion

@mobiusklein @edeutsch can you revert the latest owl to the previous version from 13th of April. Now OLS can not import the owl file generated.

**Comment by ypriverol** [comment]
@mobiusklein @edeutsch I have reverted to the previous version we created the owl. Please review and revert to previous version https://github.com/HUPO-PSI/psi-ms-CV/pull/269 submissions are getting stopped at PRIDE because OLS is not indexing the PSI-MS.

**Comment by mobiusklein** [comment]
@ypriverol I pushed a new copy yesterday that uses the old OWL workflow. Please let me know if that works for you, and what was going wrong, if it is knowable.

**Comment by mobiusklein** [comment]
It looks like OLS is indexing the MS CV again: https://www.ebi.ac.uk/ols4/ontologies/ms

**Comment by ypriverol** [comment]
Yes, since yesterday, we can close this issue and discuss the follow-up in the next PSI-MS meeting.
