### ISSUE TITLE
Add a new Enzyme

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/psi-ms-CV#27]
Can we add `lys-n` as enzyme under https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1001045&viewMode=All&siblings=false

**Comment by edeutsch** [comment]
@ypriverol @chambm please review pull request https://github.com/HUPO-PSI/psi-ms-CV/pull/28
