### ISSUE TITLE
New term for Thermo Stellar mass spectrometer

### ISSUE THREAD

**Issue by vagisha** [HUPO-PSI/psi-ms-CV#277]
### Describe the new term or terms you would like to add.

We would like to add a new term for the Thermo Stellar mass spectrometer that was just released.
https://www.thermofisher.com/us/en/home/industrial/mass-spectrometry/liquid-chromatography-mass-spectrometry-lc-ms/lc-ms-systems/orbitrap-lc-ms/stellar-mass-spectrometer.html

[Term]
id: MS:100xxxx
name: Stellar
def: "Thermo Scientific Stellar mass spectrometer contains a quadrupole mass filter, a collision cell, and a quadrupole linear ion trap mass analyzer." [PSI:PI]
is_a: MS:1000494 ! Thermo Scientific instrument model

**Comment by edeutsch** [comment]
addressed in #278
