### ISSUE TITLE
potential bug / naming of parent term

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/psi-ms-CV#282]
### Describe the question or discussion

After an obo update we get a lot of warnings of type:

Warning: while loading term 'MS:1003303' of CV 'PSI-MS': parent term name 'single identification attribute' and id 'MS:1002694' differ.

and it seems the parent term has the name ''name: single identification **result** attribute"

[Term]
id: MS:1002694
name: single identification result attribute

Is this a bug?

**Comment by timosachsenberg** [comment]
```
is_a: MS:1002664 ! interaction score derived from  crosslinking
```
also some double space here before crosslinking

**Comment by mobiusklein** [comment]
Technically, these are comments for the reader's convenience but it's good to fix them. I added a PR that patches these two problems
