### ISSUE TITLE
temperature chromatogram

### ISSUE THREAD

**Issue by chambm** [HUPO-PSI/psi-ms-CV#287]
### Describe the new term or terms you would like to add.

[Term]
id: MS:100xxxx
name: temperature chromatogram
def: "Representation of temperature versus time." [PSI:MS]
is_a: MS:1000626 ! chromatogram type

Might be measuring temperature of the sample, the instrument, or the room. Not sure how or whether that should be specified by CV. But we do have a "temperature array" term already, along with pressure and flow rate array terms (which already have chromatogram types). ProteoWizard doesn't actually use those specialized Y-axis array types (it only sets the correct unit for the intensity array, e.g. `C` or `bar`) , but it does use the chromatogram type.

**Comment by mobiusklein** [comment]
We need to add the appropriate units to the `MS:1000822|temperature array` term as well, which currently only accepts kelvins.

Do the sources that you are reading the temperature from tell you the subject of the temperature sensor?

**Comment by chambm** [comment]
You mean like Room temp or Sample temp? Yes. I'm sure I've also seen column and instrument temp traces before too.

**Comment by mobiusklein** [comment]
Yes, thank you, I realize now my question was vague.

On the one hand, we could add a temperature array for each of those objects (my grammar was wrong too), but that adds a lot of terms. We could add a second term that defines what the object being measured is, then we'd have a single `temperature chromatogram`, with as many `temperature array` entries as there are things being measured, each with a different object designation.

Which of those arrangements makes the most sense to you given the cases you have in mind?

**Comment by chambm** [comment]
We could have `temperature chromatogram` be a parent term with more specific kinds of temperature as children of it, e.g. `sample temperature chromatogram`, `instrument ambient room temperature chromatogram`, `column temperature chromatogram`, etc. But then again, Thermo RAW status logs have a plethora of temperatures:

Example RAW 1:
Ion source capillary temp
Ion source aux temp
Analyzer temp
Ambient temp
Source TMP motor temp
Source TMP bottom temp
UHV TMP motor temp
IOS heatsink temp
HVPS Peltier temp
Quad Det Temp

Example RAW 2:
Turbo Pump temp (for 3 pumps)
CPU temp (board and die)
WFG temp
Ion transfer tube temp
RD temp
RFA temp (for 1 and 2)
RFC ambient temp (for 1 and 2)
RFC Diode A & B temp (for 1 and 2, so 4 total)

So I don't think making these CV terms is all that prudent. Perhaps just a `measured element` term with a free text value?

**Comment by mobiusklein** [comment]
I agree, I thought the latter route would make the most sense, but didn't know there were this many things to record, plus this way the time array is shared. I'll sketch out some terms.
