### ISSUE TITLE
The latest release breaks again OLS. 

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/psi-ms-CV#292]
### Describe the question or discussion

@mobiusklein The latest release of PSI-MS is broken in OLS and the ontology has been removed from OLS.

**Comment by tobiasko** [comment]
Email from OLS support:

Hi Tobi,

The MS ontology is not currently available in OLS latest release, reason 
being one of the imports used in MS ontology is not in RDF format thats 
why MS terms won't be accessible in the OLS at the moment.

The MS ontology would need to be fixed by MS ontology developers for it 
to be available back in the OLS.

I hope this helps.

Cheers,
Haider

**Comment by mobiusklein** [comment]
There hasn't been a release in two weeks, this change must have been on their end. If that description is accurate, then the import process is using our `.obo` file, not our `.owl` file. The `.owl` file only imports other `.owl`s, but the `.obo` is mixed.

**Comment by tobiasko** [comment]
Hi @mobiusklein, I honestly can't judge on which end the problem is. Are you talking to each other/ working on a solution?

**Comment by mobiusklein** [comment]
I opened a PR addressing the specific issue mentioned in the message you posted #293. I can force a merge and see if that triggers anything on OLS.

**Comment by mobiusklein** [comment]
This issue was closed automatically, but the fix hasn't been verified yet. The new .obo file is now live.

**Comment by haideriqbal** [comment]
just FYI, the reason it's removed currently from OLS is the one of the imports (http://purl.obolibrary.org/obo/stato.owl) is not in the correct format and hence OLS can't process the ontology. Example of correct format (https://raw.githubusercontent.com/pato-ontology/pato/master/pato.owl)

**Comment by edeutsch** [comment]
Maybe we can just repeat STATO terms inside psi-ms and remote the import.

Term used:
      2 relationship: has_value_concept STATO:0000035 ! range
     14 relationship: has_value_concept STATO:0000036 ! outlier
      3 relationship: has_value_concept STATO:0000105 ! log signal intensity ratio
     10 relationship: has_value_concept STATO:0000237 ! standard deviation
     10 relationship: has_value_concept STATO:0000291 ! quantile
     10 relationship: has_value_concept STATO:0000401 ! sample mean

**Comment by ypriverol** [comment]
The PSI-MS is again back to OLS. @mobiusklein when you have time you can review this PR #295 and I will merge it.

**Comment by proccaserra** [comment]
@ypriverol:

STATO v1.5 available from OLS4
Please see:  https://www.ebi.ac.uk/ols4/ontologies/stato
The release process has been fixed so this issue should not happen again.

For term request, please use our tracker: https://github.com/ISA-tools/stato/issues
