### ISSUE TITLE
New ontology for TIMSTof Ultra2

### ISSUE THREAD

**Issue by FraBarSol** [HUPO-PSI/psi-ms-CV#317]
### Describe the question or discussion

Our research group has bought a new MS device: **TIMSTof Ultra2** (https://www.bruker.com/de/products-and-solutions/mass-spectrometry/timstof/timstof-ultra.html) and we have seen that there is not yet an ontology for this device.  We would greatly appreciate it if you could help us to set up one.
Thanks in advance for your help.
Kind regards
Francesca Barletta

**Comment by edeutsch** [comment]
Addressed in #320 
Now available in the latest CV
