### ISSUE TITLE
Validation error for psi-ms.obo

### ISSUE THREAD

**Issue by caetera** [HUPO-PSI/psi-ms-CV#32]
I got the following error while loading psi-ms.obo in OBOEdit

    Load Error, line 20055
    Badly formatted definition. No dbxref list found. 

Line 20055 is 
`def: "Number of extraneous mantissa bits truncated to improve subsequent compression."`
Adding `[PSI-MS]` to the end of the line 20055 fixes the error - i.e 
`def: "Number of extraneous mantissa bits truncated to improve subsequent compression." [PSI-MS]`

Since I am not quite confident with the ontology format and meaning of all fields. I would like to confirm that it is indeed a valid fix.

**Comment by edeutsch** [comment]
Thanks for reporting, addressed in PR 33
https://github.com/HUPO-PSI/psi-ms-CV/pull/33/files

**Comment by edeutsch** [comment]
fixed has been merged, thank you @ypriverol
