### ISSUE TITLE
Update / amend the MZmine software term name

### ISSUE THREAD

**Issue by nilshoffmann** [HUPO-PSI/psi-ms-CV#327]
The MZmine team has recently renamed their software to mzmine.

This would affect term MS:1002342

https://github.com/HUPO-PSI/psi-ms-CV/blob/master/psi-ms.obo#L15379

```
[Term]
id: MS:1002342
name: MZmine
def: "A framework for differential analysis of mass spectrometry data." [PMID:16403790, PMID:20650010]
is_a: MS:1001456 ! analysis software
is_a: MS:1001457 ! data processing software
```

It is not really clear, whether the change in name would warrant:
a) a simple change of the term name from MZmine to mzmine, possibly causing issues for any software relying on the exact typing of the term name, or
b) a new term for mzmine, possibly deprecating the old term (only applicable for MZmine version <4)
c) any other option that we may not be aware of?

We hope that it can be discussed, what the best way forward would be.

**Comment by edeutsch** [comment]
I'm thinking it would be best to simply rename the existing term to "mzmine" but then add a synonym "MZmine".

**Comment by edeutsch** [comment]
At call, agreed to go the mzmine with synonym route. Create a PR.
