### ISSUE TITLE
New term for Orbitrap Exploris GC 240 Mass Spectrometer

### ISSUE THREAD

**Issue by vagisha** [HUPO-PSI/psi-ms-CV#334]
### Describe the new term or terms you would like to add.

A Panorama user requested the addition of the Orbitrap Exploris GC 240 Mass Spectrometer.
https://www.thermofisher.com/order/catalog/product/BRE725537

[Term]
id: MS:100xxxx
name: Orbitrap Exploris GC 240
def: Orbitrap Exploris GC 240 Mass Spectrometer [PSI:PI]
is_a: MS:1000494 ! Thermo Scientific instrument model

**Comment by edeutsch** [comment]
Addressed is PR #335
