### ISSUE TITLE
Add a `scan number` term

### ISSUE THREAD

**Issue by fcyu** [HUPO-PSI/psi-ms-CV#343]
### Describe the new term or terms you would like to add.

For a long time, several search engines, including MSFragger and Comet (correct me if I am wrong), use `scan number` to identify/index a scan/spectrum. Using a single integer is faster and memory more efficient compared to using a string.

As far as I know, there are two major approaches to get a `scan number` from a spectrum's metadata

1. `index + 1`
2. Extract the `scan number` from the `id`. For example, given a Thermo id `controllerType=0 controllerNumber=1 scan=5`, the `scan number` is 5

The first approach has issues: if the mzML file is a subset of the original mzML, the `index` is re-assigned starting from 0, which makes the `scan number` different from those in the original mzML. A typical example is that, in FragPipe, MSFragger generates `_(un)calibrated.mzML` files only containing MS2 scans, for downstream tools to use. There would be problems if using `index+1` as the `scan number`.

The second approach works well for most Thermo data because the spectrum `id` is "1-D": only the `scan` changes in the `controllerType=0 controllerNumber=1 scan=N` format. We extract the `N` as the `scan number`. But for the data from some other venders, this approach doesn't work because there are multiple fields changing in the spectrum `id`. For example, `function=2 process=0 scan=1`: both `function` and `scan` change from scan to scan. Due to this reason, we discontinue the support of Waters and SCIEX data.

Recently, several users (e.g., https://github.com/Nesvilab/MSFragger/issues/324 and https://x.com/michaellazear/status/1782905716896100437) request us to bring the support back. It would make the life much easier if those data index the scans using `1-D` schema. Thus, I proposed to add a `scan number` term to be used by mzML, pepXML, and other XML-based files. 

I hope my explanations are clear. Let me know if you have any questions.

Best,

Fengchao

**Comment by mobiusklein** [comment]
Hello,

I may be missing a nuance here, but there are already terms to support just representing scan numbers. The exact match being [`MS:1003057|scan number`](https://www.ebi.ac.uk/ols4/ontologies/ms/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMS_1003057).

If you want to use the scan number in the context of a nativeID, there is [`MS:1000776|scan number only nativeID format`](https://www.ebi.ac.uk/ols4/ontologies/ms/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMS_1000776), but this doesn't solve the root problem in the MSFragger issue as it still decouples the reference from the original spectrum.

The `scan number` term is already valid in mzML's `scan` element, but would require adding additional parents to make it use-able in mzIdentML's `SpectrumIdentificationResult`.

What are the precise contexts you want to use refer to `scan number`s in?

**Comment by fcyu** [comment]
Thank you so much for the prompt reply. I was not aware that there is a [MS:1003057|scan number](https://www.ebi.ac.uk/ols4/ontologies/ms/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMS_1003057). Thanks for pointing it out.

> What are the precise contexts you want to use refer to scan numbers in?

I would like to let MSFragger write the `scan number`, which is used in the pepXML and psm.tsv files, to the `_(un)calibrated.mzML` and `_sub.mzML` files, so that the downstream tools, such as IonQuant, PTM Shepherd and PTMProphet (not so sure about this one), can locate the correct scan/spectrum based on the `scan number` in the pepXML and psm.tsv files. The `id` or `index` won't work in some cases I mentioned in the previous message.

I was playing with the [MS:1003057|scan number](https://www.ebi.ac.uk/ols4/ontologies/ms/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMS_1003057) a little bit today, and have the questions: will it will break the [mzML schema](https://github.com/HUPO-PSI/mzML/blob/master/schema/schema_1.1/mzML1.1.1.xsd) because there is no `MS:1003057` in the schema? It is totally fine if you don't know the answers. Maybe I should ask the https://github.com/HUPO-PSI/mzML .

Best,

Fengchao

**Comment by mobiusklein** [comment]
That term is valid to be used in `<scan>` elements because `MS:1003057` is a child of [`MS:1000503|scan attribute`](https://www.ebi.ac.uk/ols4/ontologies/ms/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMS_1000503?lang=en) which is called out in the CV mapping rules here: https://peptideatlas.org/tmp/mzML1.1.0.html#scan.

That particular term is not explicitly required, and admittedly is redundant in the main usecase because in virtually all RAW->mzML conversions, there is a 1:1 mapping between the addressable entities we speak of as scans and `<spectrum>` elements, hence there's usually only one element in the `<scanList>` element under `<spectrum>` and the "no combination" term used. This makes it analogous to `spectrum@index` (speaking XPath) and not worth emitting.

You could write `scan number` out if you were writing a subset of spectra to mzML to preserve the original scan number if you wanted to. Another option in your case would be to devolve to `scan number only nativeID format` in your intermediate mzML files, but set the `scan@externalSpectrumID` to the original RAW nativeID there, and that'd be valid too. It all depends upon how you currently traverse mzML files and which change requires the least invasive changes.

**Comment by chambm** [comment]
What would MSFragger write for Waters and Sciex nativeIDs?

**Comment by fcyu** [comment]
Hi @chambm , I am implementing the following because it makes senses and seems to be the most straightforward. Let me know if you have any suggestions or comments.

> Another option in your case would be to devolve to scan number only nativeID format in your intermediate mzML files, but set the scan@externalSpectrumID to the original RAW nativeID there, and that'd be valid too. It all depends upon how you currently traverse mzML files and which change requires the least invasive changes.

I wanted to reply @mobiusklein 's suggestion after I implement and test it, but since Matt asked, I will just reply.

> That term is valid to be used in <scan> elements because MS:1003057 is a child of [MS:1000503|scan attribute](https://www.ebi.ac.uk/ols4/ontologies/ms/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMS_1000503?lang=en) which is called out in the CV mapping rules here: https://peptideatlas.org/tmp/mzML1.1.0.html#scan.

Thank you for pointing it out. It is interesting that the schema I found ([mzML schema](https://github.com/HUPO-PSI/mzML/blob/master/schema/schema_1.1/mzML1.1.1.xsd)) doesn't have what you said. Maybe I am looking at the wrong place.

@mobiusklein Your answers are very informative and helpful. Solved my puzzles and saved me a lot of time.

Thanks,

Fengchao

**Comment by chambm** [comment]
> Another option in your case would be to devolve to scan number only nativeID format in your intermediate mzML files

It's a reasonable approach if you must keep your intermediate mzML in sync with some other output files that cannot store the nativeID. At least it will definitely be possible for downstream software to combine those files and still get the nativeID back.


> Thank you for pointing it out. It is interesting that the schema I found ([mzML schema](https://github.com/HUPO-PSI/mzML/blob/master/schema/schema_1.1/mzML1.1.1.xsd)) doesn't have what you said. Maybe I am looking at the wrong place.

MzML is a controlled vocabulary based format. Wouldn't it be ridiculous if the mzML maintainers had to update the mzML schema every time a new instrument is released, or if to avoid that problem it supported any arbitrary string in the official "instrument" attribute? Its design philosophy is laid out in the [specification document](https://github.com/HUPO-PSI/mzML/raw/master/specification_document/mzML1.1.0_specificationDocument.doc):

> Since the development of mzML brought together many different philosophies, the primary mzML designers agreed on the following design principles that would guide its development:
> 
>     1. Keep the format simple. Many elaborate extensions were proposed but most were rejected in favour of a simple implementation.
>     2. Minimize alternate ways of encoding the same information. Such flexibility, while sometimes touted as a benefit for some products, is bad for data formats.
>     3. Build in some flexibility for encoding new important information but keep the format stable. There is a strong desire from companies that develop software for their customers to keep the data format stable over long periods of time with updates to an auxiliary file.
>     4. Support the features of mzData and mzXML but not a lot more in version 1.0. Only support for SRM data was added (which is also supported in the latest mzXML 3.1 and thus not really new).
>     5. Finish version 1.0 of the format soon with the resources available. It was felt that the greatest community benefit would be to resolve the mzData/mzXML duality rather than expend limited resources on new features.
> 
> There was great temptation to add support for many new kinds of data and representation possibilities. There are many enhancements that have been suggested, but the small group of volunteers that have actively developed this format have opted to focus on the primary goal set before us: develop a single format that the vendors and current software can easily support and thereby obsolete mzData and mzXML. The enhancements not considered compatible with this goal will be entertained for mzML 2.0
> 
> One of the aspects of mzXML that enabled its very swift adoption was a ready set of open source tools that implemented the format. With these tools many users were able to begin using the format immediately without coding their own software. Therefore, to insure that mzML is a format that will be adopted quickly and implemented uniformly, the format is presented with several tools that write, read, and validate the format. At submission to the PSI document process, the following software will implement mzML:
> 
>     1. Two or more converters that convert from vendor formats to mzML.
>     2. The popular RAMP parser library that currently supports mzData and mzXML.
>     3. An mzML semantic validator that checks for correct implementation of files.
> 
> The mzData format was a far more flexible format than mzXML. The support of new technologies could be added to mzData files by adding new controlled vocabulary terms, while mzXML often required a full schema revision. This is evidenced by mzData still being at version 1.05 while mzXML is currently at version 3.1. However, mzData did suffer from a problem of inconsistently used vocabulary terms and there appeared several different dialects of mzData, encoding the same information in subtly different ways. This was not usually a problem for human inspection of the file, but caused difficulty writing and maintaining reader software.
> 
> This problem was been solved (it is hoped) for mzML by releasing a semantic validator with the data format. This semantic validator enforces many rules as to how controlled vocabulary terms are used, not only making sure that the terms are in the CV, but also that the correct terms are used in the correct location in the document and the required terms are present the correct number of times. This allows greater flexibility in the schema, but enforces order in how the CV terms are used. This will require the discipline of using the semantic validator, not just an XML validator. The result is that new technologies or information can be accommodated with adjustments to the controlled vocabulary and validator, not to the schema. Opinions differ on whether this is a benefit or a curse.

**Comment by fcyu** [comment]
If I understand it correctly, https://peptideatlas.org/tmp/mzML1.1.0.html is also the mzML schema, but contains more info than this file https://github.com/HUPO-PSI/mzML/blob/master/schema/schema_1.1/mzML1.1.1.xsd. So, am I looking at the wrong file?

Best,

Fengchao

**Comment by chambm** [comment]
I'd say it's a neat hybrid view of the schema and the CV mapping file. It inserts the parts of the mapping file that are relevant to each element at the specification for the element. It's not an XML schema though, that is the XSD file.

**Comment by mobiusklein** [comment]
@fcyu are there any lingering points for discussion here that you need time to test , or can we close this issue?

**Comment by fcyu** [comment]
I think you can close this issue. Thank you again for answer my questions.

Best,

Fengchao
