### ISSUE TITLE
OBO editor not rendering

### ISSUE THREAD

**Issue by danielsauceda** [HUPO-PSI/psi-ms-CV#344]
Howdy,

I am attempting to visualize the psi-ms.obo file in obo-edit 2.3.1 for the purposes better understanding the mzml format. I have found a number of entries that essentially break the java renderer. I'm noticing that a common issue is the escape characters in the regex expressions. "undefined terms" particularly in the "subset category", Linking to xsd:string and xsd:integer. I am curious if there are work arounds or if an alternative editor is now used

Thanks

**Comment by edeutsch** [comment]
It is my understanding that OBO-Edit has been long deprecated and not recommended for use anymore.
Apparently Protege is now the recommended ontology editor tool.
However, if you don't need to edit, and you just want to view and explore the CV, OLS is a web-based viewer:
https://www.ebi.ac.uk/ols4/ontologies/ms
https://www.ebi.ac.uk/ols4/ontologies/ms/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMS_1003028

Or BioPortal is pretty nice, too:
https://bioportal.bioontology.org/ontologies/MS/?p=classes&conceptid=root
https://bioportal.bioontology.org/ontologies/MS/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1003028&jump_to_nav=true

Does that perhaps more easily fill your need?

**Comment by edeutsch** [comment]
Closing. Please reopen if more information is needed.
