### ISSUE TITLE
Request Term for SHA-256

### ISSUE THREAD

**Issue by sneumann** [HUPO-PSI/psi-ms-CV#52]
```
[Term]
id: MS:1000XXX
name: SHA-256
def: "SHA-256 (member of Secure Hash Algorithm-2 family) is a cryptographic hash function designed by the National Security Agency (NSA) and published by the NIST as a U. S. government standard. It is also used to verify file integrity." [PSI:MS]
xref: value-type:xsd\:string "The allowed value-type for this CV term."
is_a: MS:1000561 ! data file checksum type
```
We could add `(deprecated)` to other terms:
`NIST formally deprecated use of SHA-1 in 2011` and MD-5 is deprecated even longer. 
Yours,
Steffen

**Comment by edeutsch** [comment]
Seems like a good addition if you want to use it. I would not add `(deprecated)` to the term names or tag them as deprecated because they are still in wide use. But it is certainly fine to add to the definition that NIST formally deprecated it in 2011.

**Comment by sneumann** [comment]
Indeed, I wasn't clear enough. The deprecation notice was only intended as addition for the `def:`. 
Yours, Steffen
