### ISSUE TITLE
Validate-obo.yml does not catch duplicate IDs

### ISSUE THREAD

**Issue by sneumann** [HUPO-PSI/psi-ms-CV#55]
Hi, our validation with `fastobo-validator psi-ms.obo` 
in https://github.com/HUPO-PSI/psi-ms-CV/blob/master/.github/workflows/validate-obo.yml#L27
does not catch duplicated IDs. Unsure if any of the other (non-fast ?!) obolibrary/odkfull tools would catch that, 
but the following bash one-liner checks that there are no duplicates:
```
test "X$(grep '^id:' /data/psi-ms.obo | uniq -d)" == "X" && echo TRUE
```
Yours, Steffen

**Comment by mobiusklein** [comment]
Fixed in #58
