### ISSUE TITLE
semantically invalid mzML

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/psi-ms-CV#61]
The issue with the wrong id seems to be fixed but now wet get validation errors: 
Error: mzML file semantically invalid 'FileHandler_test_282.tmp'
Error - CV term used in invalid element: 'MS:1000497 - zoom scan' at element '/mzML/run/spectrumList/spectrum'

**Comment by chambm** [comment]
That's probably a bug in whatever wrote the file. Was it msconvert? Which vendor?

**Comment by timosachsenberg** [comment]
Hi @chambm,
Might be even own code :)
I think I could track it down to this change 
https://github.com/HUPO-PSI/psi-ms-CV/commit/a8da2d92bf100bacf3b0c9b5e539743b9574b150#diff-e8d3e8e7cde947504a15711f77561d1761c62270ee8770780d57f3e87cbc9230R3430

So my explanation right now is that this triggers a validation error (via mapping file) now because it expects the scan attribute "zoom scan"  at /mzML/run/spectrumList/spectrum/scanList/scan and not at /mzML/run/spectrumList/spectrum
