### ISSUE TITLE
mzMLb example file?

### ISSUE THREAD

**Issue by soerendip** [HUPO-PSI/psi-ms-CV#65]
Hi, 

I wonder if you could point me to a small mzMLb example file?

Cheers
Soren

**Comment by mobiusklein** [comment]
These are by no means finalized, but I have two:
 - An simple one at https://github.com/levitsky/pyteomics/blob/master/tests/test.mzMLb
 - A more elaborate one at https://github.com/mobiusklein/ms_deisotope/blob/master/ms_deisotope/test/test_data/20150710_3um_AGP_001_29_30.mzMLb

Disclaimer: I wrote the software that generated these files, but I am not directly involved in mzMLb's design.

**Comment by soerendip** [comment]
Thank you.
