### ISSUE TITLE
ReDU Sample Information Template suggestion

### ISSUE THREAD

**Issue by nikhof7** [HUPO-PSI/psi-ms-CV#66]
Hi,

i am currently using the "ReDU Sample Information Template v3.0" for molecular networking with GNPS. However i can't enter my used MS because it is not part of the controlled vocabulary. I'd like to suggest adding "Shimadzu GCMS-QP2010SE" to the Google sheet.

Best regards

**Comment by mobiusklein** [comment]
I've created a term in PR #67, however I don't think we maintain the [ReDU Saple Information Template](https://docs.google.com/spreadsheets/d/1v71bnUd8fiXX51zuZIUAvYETWmpwFQj-M3mu4CNsHBU/edit#gid=450198104). You may need to reach out to the GNPS team, or https://github.com/mwang87 directly to have the new term added there.

**Comment by nikhof7** [comment]
Thank you!

**Comment by nikhof7** [comment]
Thank you!
