### ISSUE TITLE
Open a Bruker timsTOF series

### ISSUE THREAD

**Issue by sneumann** [HUPO-PSI/psi-ms-CV#77]
Hi, 
currently the `timsTOF Pro` is a singleton below `Bruker Daltonics instrument model`
https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1000122&viewMode=All&siblings=false

=> ask Bruker for a list of models and create a new Series.

Yours, 
Steffen

**Comment by edeutsch** [comment]
Thanks, Steffen, I'll reach out to Bruker for their current list and we'll update.

**Comment by edeutsch** [comment]
This is mostly fixed. But just to be complete, let's add three more terms after the open PR is merged:

```
[Term]
id: MS:1003207
name: timsTOF
def: "Bruker Daltonics' timsTOF." [PSI:MS]
is_a: MS:1003123 ! Bruker Daltonics timsTOF series

[Term]
id: MS:1003208
name: timsTOF Pro 2
def: "Bruker Daltonics' timsTOF Pro 2." [PSI:MS]
is_a: MS:1003123 ! Bruker Daltonics timsTOF series

[Term]
id: MS:1003209
name: timsTOF SCP
def: "Bruker Daltonics' timsTOF SCP." [PSI:MS]
is_a: MS:1003123 ! Bruker Daltonics timsTOF series
```

**Comment by edeutsch** [comment]
@sneumann added as PR #93
