### ISSUE TITLE
PSI CV terms new instruments and configurations

### ISSUE THREAD

**Issue by HansVissers** [HUPO-PSI/psi-ms-CV#83]
### Describe the new term or terms you would like to add.

Would it be possible to update the MS ontology terms with:
 
1.	Synapt XS
2.	SELECT SERIES Cyclic IMS
3.	SELECT SERIES MRT
 
Synapt XS and SELECT SERIES Cyclic IMS can be described in terms of configuration as a Synapt G2-Si geometry.
 
SELECT SERIES MRT is a multi-reflecting time-of flight analyzer.

**Comment by edeutsch** [comment]
Thank you @HansVissers for the suggestion of new terms. Perhaps someone else does, but I don't quite understand  the intent of these terms. The first one seems like an instrument model, but the other two are not instrument models, but rather parts of instruments? Or are they instrument model names? I don't know.

I think it would help if you could provide definitions and parents terms for these three terms, so like:

Existing Waters instrument model terms and definitions are here:
https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1000126&viewMode=All&siblings=false

So, something like this:
Name: Synapt XS
Def: Waters oa-ToF based Synapt XS
is_a: Waters instrument model

Name: SELECT SERIES Cyclic IMS
Def: ??
is_a: ?

Name: SELECT SERIES MRT
Def: ??
is_a: ?

**Comment by HansVissers** [comment]
Thanks @edeutsch,

These are all new instrument models:

So, something like this:
Name: Synapt XS
Def: Waters oa-ToF based Synapt XS
is_a: Waters instrument model

Name: SELECT SERIES Cyclic IMS
Def: Waters oa-ToF based SELECT SERIES Cyclic IMS
is_a: ? Waters instrument model

Name: SELECT SERIES MRT
Def: Waters oa-ToF based SELECT SERIES MRT
is_a: Waters instrument model

**Comment by mobiusklein** [comment]
Added in #85
