### ISSUE TITLE
start and end time of a MS acquisition

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/psi-ms-CV#89]
### Describe the new term or terms you would like to add.

Dear all, 
on behalf of the PSI-QC group I'd like to request some CV terms, albeit not exclusively QC related terms. 
Yet, I sketched the terms with accessions that reflect the accession number space in which we will place 
(as agreed in the joint telco after #80) our qc-cv terms for a merge with PSI-MS. But that will come next week, 
and these terms are somewhat independent. 

We noticed there is no value specification for the start and end time of a MS acquisition. So we'd need:
```
[Term]
id: MS:4000277
name: DateTime value
def: "A date and time specified through ISO 8601 format" [PSI:QC]
```
for
```
[Term]
id: MS:4000278
name: DateTime of acquisition start
def: "The datetime string of the acquisition start timepoint in ISO8601 format" [PSI:QC]
comment: Acquisition start time as registered by the instrument.
relationship: has_value_type MS:4000277 ! DateTime value
is_a: MS:1002435 ! data processing start time
```
and
```
[Term]
id: MS:4000279
name: DateTime of acquisition end
def: "The datetime string of the acquisition end timepoint in ISO8601 format" [PSI:QC]
comment: Acquisition end time as registered by the instrument.
relationship: has_value_type MS:4000277 ! DateTime value
is_a: MS:1000747 ! completion time
```

Example value: "2012-01-30T07:30:51"

However, for the `relationship: has_value_type` there is a DateTime specification [in another onto already](https://www.ebi.ac.uk/ols/ontologies/genepio/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGENEPIO_0002148), idk if we should import and reuse as `GENEPIO:0002148 ! date value specification (ISO 8601)`

**Comment by bittremieux** [comment]
The dbxref at the end of the `def` line should probably be `[PSI:MS]` instead.

Maybe the `name` can also be a bit more human-friendly? I.e. we don't explicitly need to specify that it's a DateTime there, as that is detailed in the definition. I'd suggest "mass spectrometry acquisition start time" and "mass spectrometry acquisition completion time" instead. The `comment`s can also specify what kind of instrument (mass spectrometer), unless we explicitly want to leave this more general?

**Comment by mobiusklein** [comment]
It's probably not necessary to import another CV for a single term. The only value of doing so would be to allow an automated reasoner to order across the two CVs. 

Just in case we end up with someone wanting to use this on a non-MS detector, how about we phrase it this way:
```
[Term]
id: MS:4000277
name:  ISO 8601 date time value
def: "A date and time specified through ISO 8601 format" [PSI:MS]

id: MS:4000278
name: instrument acquisition start time
def: "The date and time of the instrument data acquisition start timepoint in ISO8601 format" [PSI:MS]
comment: Acquisition start time as registered by the instrument.
relationship: has_value_type MS:4000277 ! ISO 8601 date time value

[Term]
id: MS:4000279
name: instrument acquisition end time
def: "The date and time of the instrument data acquisition end timepoint in ISO8601 format" [PSI:MS]
comment: Acquisition end time as registered by the instrument.
relationship: has_value_type MS:4000277 ! ISO 8601 date time value
```

I've removed the two is-a relationships because the terms they were associated with are for data processing, we use to talk about an algorithm transforming the acquired instrument signal.

**Comment by edeutsch** [comment]
These terms seem fine to me. Do we want these to be in the 4000000 series or in the 1000000 series?
Also, I am skeptical that the `comment` fields are a useful inclusion. Do we need them? Is "as registered by the instrument" an important clarification here?
