### ISSUE TITLE
PeakForest as new software term

### ISSUE THREAD

**Issue by fgiacomoni** [HUPO-PSI/psi-ms-CV#90]
### What is the new software's name?

PeakForest

### Describe the software briefly.

A comprehensive infrastructure to organize, curate and share a multi- instrument spectral library for metabolomics data annotation developed and distributed by the French National infrastructure in metabolomics and fluxomics (MetaboHUB).

### Software type

MS:1003207 ! library creation software, MS:1002878 ! small molecule analysis software

### Describe any additional information.

https://peakforest.org/

**Comment by fgiacomoni** [comment]
PeakForest is an infrastructure deployable in a lab and allowing to create compound and spectral libraries. IN this system we propose a MZML export and would like to indicate the source of the spectra (the software term as describe in MZML spec).

**Comment by chambm** [comment]
MzML is not really intended for spectral libraries but it can be twisted to at least store the peaks. Have you checked out the [mzSpecLib](https://github.com/HUPO-PSI/mzSpecLib)? @mobiusklein what's the status on how to indicate where spectral library spectra came from?

**Comment by fgiacomoni** [comment]
We use it in "one by one" spectral export functionality, not for the whole lib in one export.

**Comment by mobiusklein** [comment]
There will be a new term "library creation software", which was supposed to be added in one of the two previous batches of new terms, but apparently my script didn't pick it up. I'll add it shortly.

**Comment by fgiacomoni** [comment]
match perfectly for PeakForest!

**Comment by fgiacomoni** [comment]
@mobiusklein, can you come back to me when new terms are included in the ontology (and get identifiers). I will modify my submission with the "library creation software" term.

**Comment by fgiacomoni** [comment]
I updated my submission with MS:1003207 ! library creation software.. Thank you

**Comment by edeutsch** [comment]
@fgiacomoni added as PR #93 
please review: https://github.com/HUPO-PSI/psi-ms-CV/pull/93/files

**Comment by fgiacomoni** [comment]
Everything is fine! Thank you very much.
