### ISSUE TITLE
W4M as new software term

### ISSUE THREAD

**Issue by fgiacomoni** [HUPO-PSI/psi-ms-CV#91]
### What is the new software's name?

Workflow4Metabolomics

### Describe the software briefly.

The collaborative portal dedicated to metabolomics data processing, analysis and annotation for Metabolomics community under Galaxy developed and supported by the French National infrastructure in metabolomics & fluxomics (MetaboHUB) and the French Institute of Bioinformatics (IFB).

### Software type

MS:1001455 ! acquisition software, MS:1001456 ! analysis software, MS:1001457 ! data processing software, MS:1002414 ! postprocessing software, MS:1002878 ! small molecule analysis software, MS:1002964 ! lipidomics analysis software

### Describe any additional information.

https://workflow4metabolomics.org/

**Comment by chambm** [comment]
I like Galaxy as a platform and have developed tool wrappers and containerized analysis flavors for it, but it seems odd to me to classify it as any of those software types. To me it is a dataset and [scientific workflow management system](https://en.wikipedia.org/wiki/Scientific_workflow_system). It runs tools which are those software types (except acquisition software, I've never heard of an instrument acquiring data with Galaxy?).

It would the same as classifying snakemake, cromwell, KNIME, or one of many other workflow management systems as those software types.

How would you use the term?

**Comment by fgiacomoni** [comment]
Hi Matt,
W4M is galaxy based but fully dedicated to metabolomics data analysis. Strictly, you're right when you said it is not a software. Galaxy is a workflow manager and W4M is a workflow manager for metabolomics with tools for small molecule and lipids analysis and covering all treatment steps (preprocessing, stats, annotation, post processing...). I'm agree with you to remove MS:1001455. 
We would like to use this term as metadata to characterize metabolomics raw datasets in our information system and in spectral MZML export from PeakForest database.

Thank you for your review.

**Comment by chambm** [comment]
I think you should use the individual tools' terms in the mzML, not the workflow system's. For example, there are quite a few pipelines that convert vendor data to mzML with msconvert; it is msconvert doing the processing, not the pipeline software, so it puts the ProteoWizard software CV term in there for the "Conversion to mzML" dataProcessing step (pwiz being the name of the overall project). So I suggest whatever Galaxy tool you are running that creates the mzML, it should put its software term in there for the "Conversion to mzML" dataProcessing step.

**Comment by fgiacomoni** [comment]
Ok Matt, I understand your point of view and finally may be it was not a good idea to submit W4M as term. Thank you for your review. A last question: do you have connection with the EDAM ontology?

**Comment by edeutsch** [comment]
Thank you for the discussion. @fgiacomoni are you content to close this issue then?
